# -*- coding: utf-8 -*-
"""capstone project infosys 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QwaPATAUm401d4JVEfG3gEE3Po11nfs1
"""

!pip install streamlit google-generativeai

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import google.generativeai as genai
# 
# # ===============================
# # Configure Gemini API
# # ===============================
# GEMINI_API_KEY = "YOUR_GEMINI_API_KEY"
# 
# genai.configure(api_key=GEMINI_API_KEY)
# 
# model = genai.GenerativeModel("gemini-2.5-flash")
# 
# # ===============================
# # Streamlit Page Configuration
# # ===============================
# st.set_page_config(
#     page_title="AI Learning Buddy - Dear Tejasri",
#     page_icon="🎓",
#     layout="centered"
# )
# 
# # ===============================
# # App Header
# # ===============================
# st.title("🎓 AI Learning Buddy")
# st.subheader("🤖 Dear Tejasri")
# 
# # ===============================
# # Topic Selection
# # ===============================
# topic = st.text_input(
#     "Enter Topic",
#     value="Machine Learning Fundamentals"
# )
# 
# # ===============================
# # Chat History
# # ===============================
# if "messages" not in st.session_state:
#     st.session_state.messages = []
# 
# # ===============================
# # Display Previous Chat Messages
# # ===============================
# for message in st.session_state.messages:
#     with st.chat_message(message["role"]):
#         st.markdown(message["content"])
# 
# # ===============================
# # Chat Input
# # ===============================
# user_input = st.chat_input("Ask Dear Tejasri...")
# 
# if user_input:
# 
#     st.session_state.messages.append(
#         {"role": "user", "content": user_input}
#     )
# 
#     with st.chat_message("user"):
#         st.markdown(user_input)
# 
#     # Build conversation history
#     history = ""
# 
#     for msg in st.session_state.messages:
#         history += f'{msg["role"]}: {msg["content"]}\n'
# 
#     # AI Prompt
#     prompt = f"""
# You are an AI Learning Buddy named "Dear Tejasri".
# 
# Current Topic:
# {topic}
# 
# Conversation History:
# {history}
# 
# Instructions:
# 
# - If the current topic is "Machine Learning Fundamentals", follow the predefined lesson sequence exactly.
# 
# - If another topic is selected, first create a beginner-friendly lesson plan for that topic and then teach it step by step.
# 
# Teaching Workflow:
# 
# 1. In simple language.
# 2. In technical terms.
# 3. Why it is important?
# 4. Two real-life applications.
# 5. Simple analogy.
# 6. Iinteractive question.
# 7. Wait for the learner's reply.
# 8. Give a short summary.
# 9. Conduct a quiz:
#    - 5 MCQs
#    - 2 True/False
#    - 2 Short Answer
#    - 1 Real-world Question
# 10. Do not reveal answers immediately.
# 11. Evaluate learner answers.
# 12. Calculate score.
# 13. Explain mistakes.
# 14. Suggest revision topics.
# 15. Give one practice exercise.
# 16. Ask:
#    "Are you ready for the next lesson?"
# 
# Never teach multiple lessons at once.
# 
# Always remember previous lessons using the conversation history.
# 
# Answer only questions related to the selected topic.
# """
# 
#     response = model.generate_content(prompt)
# 
#     answer = response.text
# 
#     st.session_state.messages.append(
#         {"role": "assistant", "content": answer}
#     )
# 
#     with st.chat_message("assistant"):
#         st.markdown(answer)

!python app.py

!nohup streamlit run app.py --server.port 8501 > streamlit.log 2>&1 &

!cat streamlit.log

!npm install -g localtunnel

!lt --port 8501

!pip show streamlit

import streamlit as st
print(st.__version__)

!python app.py

!pip uninstall -y streamlit

!pip install streamlit==1.39.0

